namespace BounceTales;

public enum LevelID
{
    MISTY_MORNING = 0,
    UNFRIENDLY_FRIENDS = 1,
    SEEKING_ANSWERS = 2,
    BUMPY_CRACKS = 3,
    SECRET_STALKWAY = 4,
    INTO_THE_MINES = 5,
    A_GLOOMY_PATH = 6,
    RUMBLING_SOUNDS = 7,
    TRAPPED_IN_MACHINE = 8,
    TUNNEL_OF_TREASURES = 9,
    WICKED_CIRCUS = 10,
    HUNTING_COLOURS = 11,
    ALMOST_THERE = 12,
    FINAL_RIDE = 13,
    FANTASTIC_FAIR = 14,
    LEVEL_IDX_MAX = 15,

    GAME_CLEAR_LEVEL = FINAL_RIDE
}
